FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/alpine:latest

WORKDIR /
# 下载linux x86_64静态二进制
RUN wget https://github.com/heiher/hev-socks5-server/releases/download/2.12.0/hev-socks5-server-linux-x86_64 -O /hev-socks5-server \
    && chmod +x /hev-socks5-server

EXPOSE 1080
ENV LISTEN=0.0.0.0:1080
ENV USER=user
ENV PASS=123456

CMD ["sh", "-c", "/hev-socks5-server --listen $LISTEN --auth $USER:$PASS"]
